In [1]:
import numpy as np

In [2]:
list = list(range(10))

In [6]:
list.extend([-10, -8])

In [4]:
list[-1:0]

[]

In [11]:
list[-1:-len(list)]

[]

In [12]:
list[-1]

-8

In [14]:
list[-3]

[-10, -8]

In [15]:
list[-4]

9

In [35]:
def arrays(arr):
    arr.sort()
    get = np.array(arr, float)
    return get

In [37]:
arrays([1, 3, 0, 2])

array([0., 1., 2., 3.])

In [38]:
arr

array([3, 7, 2])

In [39]:
range(-1, -len(arr), -1)

range(-1, -3, -1)

In [40]:
list(range(-1, -len(arr), -1))

TypeError: 'list' object is not callable

In [44]:
len(arr)

3

In [45]:
range(-1, -3, -1)

range(-1, -3, -1)

In [46]:
for _ in range(-1, -3, -1):
    print(_)

-1
-2


In [47]:
list(range(-1, -4, -1))

TypeError: 'list' object is not callable

In [53]:
def arrays(arr):
    arr = arr[_ in range(-1, -len(arr), -1)]
    arr = np.array(arr, float)
    return arr

In [54]:
arrays([1, 2, 3, 4, -8, -10])

array(2.)

In [56]:
arr[_ in range(-1, -len(arr), -1)]

array([[3, 7, 2]])

In [57]:
arr

array([3, 7, 2])

In [58]:
arr[-1]

2

In [60]:
[_ in range(-1, -len(arr), -1)]

[True]

In [61]:
for _ in range(-1, -len(arr), -1):
    print(_)

-1
-2


In [67]:
arr = '1 2 3 4 -8 -10'

In [68]:
arr.strip().split(' ')

['1', '2', '3', '4', '-8', '-10']

In [69]:
list = arr.strip().split(' ')

In [70]:
list[::-1]

['-10', '-8', '4', '3', '2', '1']

In [74]:
def arrays(arr):
    arr = arr.strip().split(' ')
    arr = arr[::-1]
    arr = np.array(arr, float)
    return arr

In [75]:
arrays('1 2 3 4 -8 -10')

array([-10.,  -8.,   4.,   3.,   2.,   1.])

## 리스트 인덱싱 
## 입력 인수의 자료형과 자료구조 
## 변수에 저장 혹은 출력?

- **transpose and flatten**

In [76]:
STDIN = '''2 2
1 2
3 4'''

In [77]:
STDIN

'2 2\n1 2\n3 4'

In [78]:
def tp(arr):
    arr = arr.split('\n')
    arr = [x.split() for x in arr]
    return arr

In [79]:
tp(STDIN)

[['2', '2'], ['1', '2'], ['3', '4']]

In [93]:
def tp(arr):
    arr = arr.split('\n')
    arr = [x.split() for x in arr]
    arr = np.array(arr, int)
    arr = np.array(arr[1:], int).reshape(arr[0])
    print(np.transpose(arr))
    print(arr.flatten())

In [92]:
tp(STDIN)

[[1 3]
 [2 4]]
[1 2 3 4]


array([[1, 2],
       [3, 4]])

#### python에서는 np.array(배열, dtype)에서 dtype으로 string을 integer로 바꿀 수가 없다 ...
### ?파이썬에서 자료형 바꾸는 방법은?
### ?파이썬 map 함수?

In [104]:
STDIN = open('C:\\Users\\Aaron Cho\\project\\PDA\\Hackers\\STDIN.txt').read()

In [96]:
def tp(arr):
    arr = [x.split() for x in arr]
    arr = np.array(arr, int)
    arr = np.array(arr[1:], int).reshape(arr[0])
    return(np.transpose(arr))
    return(arr.flatten())

In [98]:
tp(STDIN)

array([[1, 3],
       [2, 4]])

In [101]:
np.array(arr.split(), int).reshape((2, 3))

array([[  1,   2,   3],
       [  4,  -8, -10]])

In [108]:
np.array(arr.split(), int).reshape((2, 3)).flatten()

array([  1,   2,   3,   4,  -8, -10])

In [109]:
n, m = map(int, input().split())
array = np.array([input().strip().split() for _ in range(n)], int)
print(array.transpose())
print(array.flatten())


'''2 2


ValueError: invalid literal for int() with base 10: "'''2"

In [110]:
map(int, '''2 2
1 3
2 4''')

In [112]:
'''2 2
1 3
2 4'''.split()

['2', '2', '1', '3', '2', '4']

In [113]:
map(int, '''2 2
1 3
2 4'''.split())

In [114]:
type(map(int, '''2 2
1 3
2 4'''.split()))

map

In [115]:
[x for x in map(int, '''2 2
1 3
2 4'''.split())]

[2, 2, 1, 3, 2, 4]

In [119]:
np.array([[2, 2], 
         [1, 3], 
         [2, 4]])

array([[2, 2],
       [1, 3],
       [2, 4]])

In [120]:
n, m = map(int, '''2 2
1 2
3 4'''.split())

ValueError: too many values to unpack (expected 2)

In [129]:
n = '20'
i
if n % 2 == 0:
    if n > 20 or (n >= 2 and n <= 5):
        print('Not Weird')
    else:
        print('Weird')
else:
    print('Weird')

TypeError: not all arguments converted during string formatting

- Arithmetic Operators

In [130]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    print(a+b)
    print(a-b)
    print(a*b)

a = 3, b = 5


ValueError: invalid literal for int() with base 10: 'a = 3, b = 5'

### ? 한꺼번에 여러개를 print할 수 있는 방법은?

In [133]:
a = 3
b = 5
print(a+b a-b a*b)

SyntaxError: invalid syntax (Temp/ipykernel_113016/912574881.py, line 3)

- **loop**

In [135]:
for _ in range(5):
    print(_**2)

0
1
4
9
16


### 이용해야 하는 변수를 잘 생각해야 하고 
### 문제가 묻는 것도 잘 봐야한다

- **make a function**

In [142]:
def is_leap(year):
    if year % 400 == 0:
        leap = True
    elif year % 4 == 0:
        if year % 100 != 0:
            leap = True
    else:
        leap = False
    return leap

In [143]:
is_leap(800)

True

### if는 위에서 조건이 걸리면 빠져나와지니까 예외를 위에 둬야한다

- **print function**

In [156]:
string = ''
for _ in range(n+1):
    string += str(_)

TypeError: can only concatenate str (not "int") to str

In [145]:
str(3)

'3'

In [147]:
[_ for x in range(3)]

[4, 4, 4]

In [149]:
[str(_) for x in range(3+1)]

['4', '4', '4', '4']

In [150]:
list(range(3))

TypeError: 'list' object is not callable

In [151]:
str(range(3))

'range(0, 3)'

In [152]:
for _ in range(3):
    print(_)

0
1
2


In [153]:
for _ in range(3):
    print(str(_))

0
1
2


In [158]:
'a' + 'b'

'ab'

In [162]:
List = []
for i in range(3):
    List.append(i)
''.join(List)

TypeError: sequence item 0: expected str instance, int found

In [164]:
List

[0, 1, 2]

In [166]:
List = []
for i in range(3):
    List.append(str(i))
print(''.join(List[1:]))

12
