- triangle quest 2

In [1]:
range(3, 3)

range(3, 3)

In [2]:
list(range(3, 3))

[]

In [3]:
list(range(3, 4))

[3]

In [4]:
str(range(3, 4))

'range(3, 4)'

In [5]:
range(1, 2) + range(1, 1, -1)

TypeError: unsupported operand type(s) for +: 'range' and 'range'

In [6]:
range(1, 1, -1)

range(1, 1, -1)

In [7]:
list(range(1, 1, -1))

[]

In [8]:
list(range(1, 0, -1))

[1]

In [12]:
list(range(1, 3)) + list(range(1, 0, -1))

[1, 2, 1]

In [13]:
list(range(1, 2)) + list(range(1, 0, -1))

[1, 1]

In [14]:
list(range(1, 2)) + list(range(0, 0, -1))

[1]

In [15]:
list(range(1, 3)) + list(range(1, 0, -1))

[1, 2, 1]

In [17]:
numbers = list(range(1, 3)) + list(range(1, 0, -1))

In [18]:
map(str, numbers)

In [19]:
list(map(str, numbers))

['1', '2', '1']

In [20]:
numbers = list(map(str, numbers))

In [23]:
import functools
functools.reduce(lambda x, y: x + y, numbers, '')

'121'

In [26]:
numbers = list(range(3, 10))

In [27]:
numbers

[3, 4, 5, 6, 7, 8, 9]

In [28]:
numbers[-1:-5:-1]

[9, 8, 7, 6]

In [29]:
numbers[-5:-1]

[5, 6, 7, 8]

In [32]:
for i in range(1, 6):
    print(((10**i)-1) / 9)

0.0
1.0
11.0
111.0
1111.0


In [33]:
for i in range(1, 6):
    print((((10**i)-1) / 9)**2)

1.0
121.0
12321.0
1234321.0
123454321.0


# 입력코드 (1) > and it works 

In [34]:
for i in range(1, 6):
    print(int((((10**i)-1) / 9)**2))

1
121
12321
1234321
123454321


# 입력코드 (2) 

In [35]:
for i in range(1, int(input()) + 1):
    numbers = list(range(1, i+1))
    print(''.join(numbers + numbers[-2:-5:-1]))

5


TypeError: sequence item 0: expected str instance, int found

# 입력코드 (3)

In [36]:
for i in range(1, int(input()) + 1):
    numbers = map(str, list(range(1, i+1)))
    print(''.join(numbers + numbers[-2:-5:-1]))

5


TypeError: 'map' object is not subscriptable

# 입력코드 (4) 

In [37]:
for i in range(1, int(input()) + 1):
    numbers = list(map(str, list(range(1, i+1))))
    print(''.join(numbers + numbers[-2:-5:-1]))

5
1
121
12321
1234321
12345432


In [38]:
for i in range(1, int(input()) + 1):
    numbers = list(map(str, list(range(1, i+1))))
    print(''.join(numbers + numbers[-(i-2):-(i+1):-1]))

5
11
121
123321
1234321
12345321


In [42]:
for i in range(1, int(input()) + 1):
    numbers = list(map(str, list(range(1, i+1))))
    print(''.join(numbers + numbers[-2::-1]))

5
1
121
12321
1234321
123454321


- triangle quest 

In [43]:
for _ in range(5):
    print(5) * _

5


TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

# 입력코드 (1)

In [ ]:
for i in range(1, N):
    print(i*(((10**i)-1)/9))

# 입력코드 (2) 

In [45]:
N = int(input())
for i in range(1, N):
    print(int(i*(((10**i)-1)/9)))

5
1
22
333
4444


- Integers come in all sizes

# 입력코드 (1)

In [ ]:
a, b, c, d = map(int, input().split())
number = (a**b) + (c**d)
print(int(number))

# 입력코드 (2)

In [ ]:
a, b, c, d = [int(input()) for _ in range(4)]
number = (a**b) + (c**d)
print(int(number))

- shape and reshape

In [ ]:
import numpy as np 
num = map(int, input().split())
list = np.array(num).reshape((3, 3))
print(list)

In [ ]:
import numpy as np 
num = map(int, input().split())
List = np.array(num).reshape((3, 3))
print(List)

In [46]:
import numpy as np 

In [47]:
num = map(int, '3 5 5 33 1 2 4'.split())

In [48]:
List = np.array(num).reshape((3, 3))

ValueError: cannot reshape array of size 1 into shape (3,3)

In [52]:
num = list(map(int, '3 5 5 33 1 2 4 5 5'.split()))

In [53]:
List = np.array(num).reshape((3, 3))

In [54]:
List

array([[ 3,  5,  5],
       [33,  1,  2],
       [ 4,  5,  5]])

In [55]:
np.array('abdsac').reshape((2, 3))

ValueError: cannot reshape array of size 1 into shape (2,3)

In [58]:
np.array(('a', 'b', 'c', 's', 'a', 'x')).reshape((3, 2))

array([['a', 'b'],
       ['c', 's'],
       ['a', 'x']], dtype='<U1')

In [ ]:
import numpy as np 
num = list(map(int, input().split()))
array = np.array(num).reshape((3, 3))
print(array)

- array mathematics

In [ ]:
import numpy as np 

N, M = map(int, input().split())

A = np.array([list(map(int, input().split())) for _ in range(N)]).reshape((N, M))
B = np.array([list(map(int, input().split())) for _ in range(N)]).reshape((N, M))

functions = ['add', 'subtract', 'multiply', 'divide', 'mod', 'power']
for function in functions:
    print(getattr(A, function)(B))

In [59]:
np.array([[1, 2, 3, 4], [4, 5, 7, 8]]).reshape((8, 1))

array([[1],
       [2],
       [3],
       [4],
       [4],
       [5],
       [7],
       [8]])

In [61]:
np.array([[1, 2, 3, 4], [4, 5, 7, 8]]).reshape((2, 4)).add(3)

AttributeError: 'numpy.ndarray' object has no attribute 'add'

In [62]:
np.add([[1, 2, 3, 4]], [5, 1, 7,2])

array([[ 6,  3, 10,  6]])

In [63]:
functions = [np.add, np.subtract, np.multiply, np.divide, np.mod, np.power]

In [65]:
for function in functions:
    print(function(np.array([1, 2, 3, 4]), np.array([5, 1, 7, 2])))

[ 6  3 10  6]
[-4  1 -4  2]
[ 5  2 21  8]
[0.2        2.         0.42857143 2.        ]
[1 0 3 0]
[   1    2 2187   16]


# 입력코드 (2)

In [ ]:
import numpy as np 

N, M = map(int, input().split())

A = np.array([list(map(int, input().split())) for _ in range(N)]).reshape((N, M))
B = np.array([list(map(int, input().split())) for _ in range(N)]).reshape((N, M))

functions = ['add' 'subtract', 'multiply', 'divide', 'mod', 'power']
for function in functions:
    print(function(A, B))

# 입력코드 (3)

In [ ]:
import numpy as np 

N, M = map(int, input().split())

A = np.array([list(map(int, input().split())) for _ in range(N)]).reshape((N, M))
B = np.array([list(map(int, input().split())) for _ in range(N)]).reshape((N, M))

functions = [np.add, np.subtract, np.multiply, np.divide, np.mod, np.power]
for function in functions:
    print(function(A, B))

# 입력코드 (4)

In [ ]:
import numpy as np 

N, M = map(int, input().split())

A = np.array([list(map(int, input().split())) for _ in range(N)]).reshape((N, M))
B = np.array([list(map(int, input().split())) for _ in range(N)]).reshape((N, M))

functions = [np.add, np.subtract,ㅠnp.multiply, np.floor_divide, np.mod, np.power]
for function in functions:
    print(function(A, B))

In [ ]:
### 예시답안 
import numpy as np 
n, m = map(int, input().split())
a, b = (np.array([input().split() for _ in range(n)], dtype = int) for _ in range(2))
print(a+b, a-b, a*b, a//b, a%b, a**b, sep = '\n')

- floor, ceil and rint

# 입력코드 (1)

In [ ]:
import numpy as np 
A = np.array(list(map(int, input().split())))
functions = [floor, ceil, rint]
for functions in functions:
    print(function(A))

# 입력코드 (2)

In [ ]:
import numpy as np 
A = np.array(list(map(float, input().split())))
functions = [floor, ceil, rint]
for functions in functions:
    print(function(A))

In [66]:
np.floor(44.4)

44.0

# 입력코드 (3)

In [ ]:
import numpy as np 
A = np.array(list(map(float, input().split())))
functions = [np.floor, np.ceil, np.rint]
for function in functions:
    print(function(A))

# 입력코드 (4)

In [ ]:
import numpy as np 
np.set_printoptions(legacy = '1.13')

A = np.array(list(map(float, input().split())))
functions = [np.floor, np.ceil, np.rint]
for function in functions:
    print(function(A))

- concatenate

In [67]:
a = np.array(list(range(5)))
b = np.array(list(range(5, 0, -1)))

In [69]:
a

array([0, 1, 2, 3, 4])

In [70]:
b

array([5, 4, 3, 2, 1])

In [68]:
np.concatenate(a, b)

TypeError: only integer scalar arrays can be converted to a scalar index

In [72]:
a_ = a.reshape((1, 5))
b_ = b.reshape((1, 5))

In [73]:
np.concatenate(a_, b_)

TypeError: only integer scalar arrays can be converted to a scalar index

In [74]:
a

array([0, 1, 2, 3, 4])

In [75]:
np.concatenate((a,b))

array([0, 1, 2, 3, 4, 5, 4, 3, 2, 1])

In [78]:
np.concatenate((a, b))

array([0, 1, 2, 3, 4, 5, 4, 3, 2, 1])

In [79]:
A = [[1, 2, 3] , [4, 5, 6]]
B = [[4, 5, 6], [0, 1, 0]]

In [80]:
np.concatenate((A, B), axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [0, 1, 0]])

In [ ]:
import numpy as np 
a, b, p = map(int, input().split())
A = np.array([list(map(int, input().split())) for _ in range(a)]).reshape((a, p))
B = np.array([list(map(int, input().split())) for _ in range(b)]).reshape((b, p))

print(np.concatenate((A, B), axis = 0))

- zeros and ones

# 입력코드 (1)

In [ ]:
import numpy as np 
shape = tuple(map(int, input().split()))

print(np.zeros(shape))
print(np.ones(shape))

In [96]:
shape = map(int, '3 3 6'.split())

In [94]:
list(shape)

[3, 3, 6]

In [85]:
print(np.zeros((*shape)))

SyntaxError: can't use starred expression here (Temp/ipykernel_25000/418825820.py, line 1)

In [97]:
for _ in shape:
    print(_)

3
3
6


In [87]:
shape

In [88]:
list(shape)

[]

In [98]:
shape = tuple(map(int, '3 3 6'.split()))

In [99]:
shape

(3, 3, 6)

In [ ]:
import numpy as np 
shape = tuple(map(int, input().split()))

print(np.zeros(shape, dtype = 'int'))
print(np.ones(shape, dtype = 'int'))

# eye and identity 

# 입력코드 (1)

In [ ]:
import numpy as np 

shape = tuple(map(int, input().split()))
array = np.eye(shape, key = 0)
print(array)

# 입력코드 (2)

In [ ]:
import numpy as np 

shape = tuple(map(int, input().split()))
array = np.eye(shape, k = 0)
print(array)

# 입력코드 (3)

In [ ]:
import numpy as np 

shape = tuple(map(int, input().split()))
array = np.eye(*shape, k = 0)
print(array)

# 입력코드 (4)

In [ ]:
import numpy as np 
np.set_printoptions(legacy = '1.13')

shape = tuple(map(int, input().split()))
array = np.eye(*shape, k = 0)
print(array)

In [ ]:
### 예시답안 
import numpy 
numpy.set_printoptions(sign = '')
print(numpy.eye(*map(int, input().split())))


- inner and outer

In [101]:
np.inner([1, 2, 3, 4], [10,6, 1, 2])

33