- Credit Card Mask
    - mask the letters all but the last 4 letters

- **first trial**

In [15]:
def maskify(cc):
    import re
    masked = re.sub('.*', '#', cc[:-5])
    rest = cc[-5:]
    return masked + rest

In [11]:
cc = ''
rest = cc[-5:]

In [12]:
rest

''

In [13]:
cc

''

In [16]:
maskify('1')

'#1'

In [17]:
re.sub('.*', '#', '1'[:-5])

'#'

In [18]:
'1'[:-5]

''

- **second trial** > **success**

In [23]:
def maskify(cc):
    import re
    masked = re.sub('.', '#', cc[:-4])
    rest = cc[-4:]
    return masked + rest

In [24]:
maskify('1')

'1'

In [25]:
maskify('')

''

In [26]:
maskify('64607935616')

'#######5616'

- **sample codes**

In [ ]:
def maskify(cc):
    return '#'*(len(cc)-4) + cc[-4:]

- so this takes that no need to really substitute # for a letter, just that it needs that amount to # to produce the result

In [ ]:
def maskify(cc):
    word = list(cc)
    for i in range(len(word)-4):
        word[i] = '#'
    return ''.join(word)
    pass

- Descending Order
    - rearange the numbers as a highest possible digit

In [28]:
numbers = list(map(str, 2512321))

TypeError: 'int' object is not iterable

In [29]:
numbers = list(str(2512321))

In [30]:
numbers

['2', '5', '1', '2', '3', '2', '1']

In [37]:
numbers.sort(reverse = True)

In [38]:
numbers

['5', '3', '2', '2', '2', '1', '1']

- list 함수에 int 못 넣음
- list의 sort 메서드에서 차순 정하는 건 reverser keyword임

- **first trial**

In [53]:
def descending_order(num):
    numbers = list(str(num))
    numbers.sort(reverse = True)
    high_num = int(''.join(numbers))
    return high_num

- **second trial**

In [54]:
def descending_order(num):
    if num >= 0:
        numbers = list(str(num))
        numbers.sort(reverse = True)
        high_num = int(''.join(numbers))
        return high_num
    else:
        pass

In [55]:
descending_order(32123)

33221

In [56]:
descending_order(42145)

54421

In [57]:
descending_order(0)

0

In [58]:
descending_order(-29128)

- **sample codes**

In [ ]:
def Descending_Order(num):
    if isinstance(num, int) and num >= 0:
        return int(''.join(sorted(str(num), reverse = True)))
    else:
        raise ValueError('Non-negative integer expected')

- 논항의 자격 조건을 확인하려고 isinstance 함수를 썼고
- 따로 변수를 만들지 않고 ''.join(), sorted(논항, reverse = True)를 한줄코드에 다 넣음

- .sort() 메서드를 안 쓰고 sorted 함수를 쓴 것도 눈여겨 볼만
- sorted 바로 쓰면 변수 설정 안 해도 됨

In [ ]:
def Descending_Order(num):
    return int(''.join(sorted(str(num))[::-1]))

- list 원소들 거꾸로 꺼내는 슬라이싱 썼네

- Equal Sides of An Array
    - return an index
    - where the sum of its left side and the sum of its right side is the same
    - if there's nothing like that, return -1
    

In [60]:
[1, 2, 5][:3].append(0)

In [62]:
sum([1, 2, 5], 0)

8

- **first trial**

In [65]:
def find_even_index(arr):
    for i in range(len(arr)):
        if sum(arr[:i], 0) == sum(arr[i+1:], 0):
            index = i
            break
        else:
            index = -1
    return index

In [66]:
find_even_index({1, 100, 50, -51, 1, 1})

TypeError: 'set' object is not subscriptable

- **second trial**

In [67]:
def find_even_index(arr):
    import numpy as np
    arr = np.array(arr)
    for i in range(len(arr)):
        if sum(arr[:i], 0) == sum(arr[i+1:], 0):
            index = i
            break
        else:
            index = -1
    return index

In [70]:
import numpy as np 
np.array({20, 10, -80, 10})

array({-80, 10, 20}, dtype=object)

- **thrid trial**

In [71]:
def find_even_index(arr):
    arr = list(arr)
    for i in range(len(arr)):
        if sum(arr[:i], 0) == sum(arr[i+1:], 0):
            index = i
            break
        else:
            index = -1
    return index

In [72]:
find_even_index({1, 100, 50, -51, 1, 1})

-1

In [73]:
list({1, 100, 50, -51, 1, 1})

[1, 50, 100, -51]

- list 함수에 set를 넣으면 순서가 지멋대로 바뀐다

In [85]:
arr = np.array(list({20, 50, 40, -3}))

In [86]:
arr

array([40, 50, 20, -3])

In [98]:
arr.shape[0]

4

In [103]:
def find_even_index(arr):
    import numpy as np
    arr = np.array(list(arr))
    index = -1
    for i in range(arr.shape[0]):
        if sum(arr[:i], 0) == sum(arr[i+1:], 0):
            index = i
            break
    return index

- 조건 만족하는 거 찾으면 if문 빠져나오는 거 어케하지?

In [104]:
find_even_index({1, 100, 50, -51, 1, 1})

-1

In [96]:
for i in [3, 1, 7, 2, 4]:
    if i == 7:
        index = i
        break
    else:
        index = -1

In [97]:
index

7

In [107]:
arr = np.array([1, 100, 50, -51, 1, 1])
index = -1
for i in range(arr.shape[0]):
    if sum(arr[:i], 0) == sum(arr[i+1:], 0):
        index = i

In [108]:
index

1

In [117]:
sum(arr[:1], 0)

1

In [118]:
sum(arr[2:], 0)

1

In [123]:
sum(arr[:0], 0)

0

In [124]:
sum(arr[1:], 0)

101

In [120]:
def find_even_index(arr):
    import numpy as np
    arr = np.array(list(arr))
    index = int()
    for i in range(arr.shape[0]):
        if sum(arr[:i], 0) == sum(arr[i+1:], 0):
            index = i
        else:
            continue
    return index if index else -1

In [121]:
find_even_index({1, 100, 50, -51, 1, 1})

-1

- 존나 뭐가 잘못됐는지 모르겄다

In [134]:
find_even_index({1, 2, 3, 4, 3, 2, 1})

-1

In [135]:
arr = np.array(list({1, 2, 3, 4, 3, 2, 1}))

In [136]:
arr

array([1, 2, 3, 4])

In [137]:
for i in range(arr.shape[0]):
        if sum(arr[:i], 0) == sum(arr[i+1:], 0):
            index = i
        else:
            continue
    

In [138]:
index

1

- 그 인풋을 온전하게 다룰 수 있는 애가 없나??

In [140]:
np.array(list({1, 100, 50, -51, 1, 1}))

array([  1,  50, 100, -51])

- **fourth trial**
    - 여러 index가 만족할 땐 제일 작은 거 뽑아야 함

In [141]:
def find_even_index(arr):
    import numpy as np
    arr = np.array(list(arr))
    index = int()
    for i in range(arr.shape[0]):
        if sum(arr[:i], 0) == sum(arr[i+1:], 0):
            index = i
            break
        else:
            continue
    return index if index else -1

- **sample codes**

In [ ]:
def fine_even_index(lst):
    left_sum = 0
    right_sum = sum(lst)
    for i, a in enumerate(lst):
        right_sum -= a
        if left_sum == right_sum:
            return i
        left_sum += a
    return -1

- index 접근을 enumerate로 했고
- 한 loop마다 sum을 새로 만들지 않았다

In [ ]:
def find_even_index(arr):
    right = sum(arr)
    left = 0
    for i, x in enumerate(arr):
        right -= x
        if right == left:
            return i
        left += x
    return -1

- 한 함수 안에서 return 한번 마주치면 그 함수는 끝
- 함수에서 return은 함수의 종료를 뜻함