- Exceptions

In [1]:
1/0

ZeroDivisionError: division by zero

In [2]:
1/#

SyntaxError: invalid syntax (Temp/ipykernel_27304/499683676.py, line 1)

In [3]:
1/int('#')

ValueError: invalid literal for int() with base 10: '#'

In [5]:
try:
    print(1/0)
except ZeroDivisionError as e:
    print('Error Code:', e)

Error Code: division by zero


In [ ]:
T = int(input())
try:
    n, m = map(int, input().split())
    print(n/m)
except ZeroDivisionError as ze:
    print('ErrorCode:', ze)
except ValueError as ve:
    print('ErrorCdoe:', ve)

In [ ]:
T = int(input())
numbers = [map(int, input().split()) for _ in range(T)]
for n, m in numbers:
    try: 
        print(n/m)
    except ZeroDivisionError as ze:
        print('ErrorCode:', ze)
    except ValueError as ve:
        print('ErrorCode:', ve)

In [12]:
numbers = [[1, 0], [0, 1], [3, 4], [100, int($)]]

SyntaxError: invalid syntax (Temp/ipykernel_27304/138522175.py, line 1)

In [13]:
for n, m in numbers:
    try:
        print(n/m)
    except ZeroDivisionError as ze:
        print('ErrorCode:', ze)
    except ValueError as ve:
        print('ErrorCode:', ve)

ErrorCode: division by zero
0.0
0.75


TypeError: unsupported operand type(s) for /: 'int' and 'str'

### 출력을 하려면
#### 어느 단계에서 오류를 발생시키는지도 중요하겠구나 

In [14]:
numbers = [['1', '0'], ['0', '1'], ['3', '4'], ['100', '$']]

In [15]:
for n, m in numbers:
    try:
        print(int(n)/int(m))
    except ZeroDivisionError as ze:
        print('ErrorCode:', ze)
    except ValueError as ve:
        print('ErrorCdoe:', ve)

ErrorCode: division by zero
0.0
0.75
ErrorCdoe: invalid literal for int() with base 10: '$'


In [ ]:
T = int(input())
numbers = [input().split() for _ in range(T)]

for n, m in numbers:
    try:
        print(int(n)//int(m))
    except ZeroDivisionError as ze:
        print('Error Code:', ze)
    except ValueError as ve:
        print('Error Code:', ve)

In [16]:
lines = [try: print(int(n) // int(m)) 
 except ZeroDIvisionError as ze: print('Error Code:', ze)
 except ValueError as ve: print('Error Code:', ve)]
]
print(*lines, sep = '\n')

SyntaxError: invalid syntax (Temp/ipykernel_27304/2093357317.py, line 1)

### 해보니까 try statement를 list comprehension에 쓸 수는 없는 듯?

- Incorrect Regex

In [18]:
import re

In [19]:
re.search('.*+', 'abcd1938##')

error: multiple repeat at position 2

In [22]:
try:
    re.search('.+*', '1234')
except Error as E:
    print(False)

NameError: name 'Error' is not defined

In [32]:
type(re.search('.', '\n'))

NoneType

In [31]:
type(re.findall('.+*', 'abcd123')) != 'list'

error: multiple repeat at position 2

In [33]:
regexs = ['.+', '.+*']
for regex in regexs:
    print(*[True if re.search(regex, 'abcde') else False])

True


error: multiple repeat at position 2

In [37]:
regex = ['.*\+', '.*+']

In [39]:
for reg in regex:
    try:
        re.search(reg, 'abcde')
        print(True)
    except Exception:
        print(False)

True
False


In [40]:
for reg in regex:
    try:
        re.search(reg, 'abcde')
        print(True)
    except re.error:
        print(False)

True
False


In [36]:
re.search('\d', 'abcde')

### 하.. 패키지 로드 잊지 마라 

In [ ]:
### 예시답안
impore re
for _ in range(int(input())):
    ans = True
    try:
        reg = re.compile(input())
        except re.error:
            ans = False
        print(ans)

- Sum and Prod

In [ ]:
import numpy as np

N, M = map(int, input().split())
arr = np.array([map(int, [a, b]) for a, b in input().split()]).reshape((N, M))
Sum = np.sum(arr, axis = 0)
Prod = np.prod(Sum)


In [42]:
import numpy as np

arr = np.array([3, 4, 5, 6, 7, 8]).reshape((3, 2))
Sum = np.sum(arr, axis = 0)
Prod = np.prod(Sum)

In [43]:
Prod

270

In [44]:
import numpy as np

arr = np.array(a, b for a, b in [[3, 4], [5, 6], [7, 8]]).reshape((3, 2))
Sum = np.sum(arr, axis = 0)
Prod = np.prod(Sum)

SyntaxError: Generator expression must be parenthesized (Temp/ipykernel_27304/110281157.py, line 3)

In [47]:
import numpy as np

arr = np.array(x for x in [[3, 4], [5, 6], [7, 8]]).reshape((3, 2))
Sum = nap.sum(arr, axis = 0)
Prod = np.prod(Sum)

ValueError: cannot reshape array of size 1 into shape (3,2)

In [49]:
import numpy as np

arr = np.array([a, b for x in [[3, 4], [5, 6], [7, 8]] for a, b in x]).reshape((3, 2))
Sum = nap.sum(arr, axis = 0)
Prod = np.prod(Sum)

SyntaxError: invalid syntax (Temp/ipykernel_27304/1214701279.py, line 3)

In [50]:
nested_list = [[3, 4], [5, 6], [7, 8]]

In [52]:
[a, b for a, b in x for x in nested_list]

SyntaxError: invalid syntax (Temp/ipykernel_27304/2565215544.py, line 1)

In [53]:
[x[0], x[1] for x in nested_list]

SyntaxError: invalid syntax (Temp/ipykernel_27304/3626033911.py, line 1)

In [ ]:
import numpy as np

N, M = map(int, input().split())

arr = np.array(map(int, ' '.join([input(), input()]).split())).reshape((N, M))
Sum = np.sum(arr, axis = 0)
Prod = np.prod(Sum)


In [54]:
arr = np.array(map(int, ' '.join(['3 4', '7 9']).split())).reshape((1, 4))

ValueError: cannot reshape array of size 1 into shape (1,4)

In [55]:
np.array(map(int, ['3', '4', '5', '6']))

array(<map object at 0x0000020574AC0B20>, dtype=object)

### map object를 array에 바로 넣을 수 없다 

In [56]:
arr = np.array(list(map(int, ' '.join(['3 4', '7 9']).split()))).reshape((1, 4))

In [57]:
arr

array([[3, 4, 7, 9]])

In [ ]:
import numpy as np

N, M = map(int, input().split())

arr = np.array(list(map(int, ' '.join([input(), input()]).split()))).reshape((N, M))
Sum = np.sum(arr, axis = 0)
Prod = np.prod(Sum)

print(Prod)

In [58]:
arr = np.array()

TypeError: array() missing required argument 'object' (pos 0)

In [59]:
arr = np.empty((2, 3))

In [60]:
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [61]:
arr[0]

array([0., 0., 0.])

In [62]:
arr[1]

array([0., 0., 0.])

In [63]:
np.add(arr, [3, 4, 5])

array([[3., 4., 5.],
       [3., 4., 5.]])

In [64]:
np.add(arr, [[3, 4, 5], [7, 8, 9]])

array([[3., 4., 5.],
       [7., 8., 9.]])

In [ ]:
import numpy as np

N, M = map(int, input().split())
arr = np.zeros((N, M))
arr = np.add(arr, [list(map(int, input().split())), 
            list(map(int, input().split()))])
Sum = np.sum(arr, axis = 0)
Prod = np.prod(Sum, axis )

print(Prod)

### np.zeros()로 배열 만들면 0.0이 default로 들어가네!!!!!!!

In [ ]:
### 예시답안 
def map_finc(y): 
    return map(int, y,split())
def sum_prod(x): 
    N, M = map_func(x) 
    array = (np.array([list(map_func(input())) for _ in range(N)]))
    print(np.prod(np.prod(np.sum(array, axis = 0))))

sample_input = input()
sum_prod(sample_input

### 한 개의 사용자 정의 함수 속에 여러 함수를 넣어 이용할 수 있다 

In [ ]:
N, M = map(int, input().split())
A = np.array([input().split() for _ in range(N)], int)
print(np.prod(np.sum(A, axis = 0), axis = 0))

- Min and Max

In [ ]:
import numpy as np 

def min1_max0(Input):
    N,M = map(int, input().split())
    arr = np.array([input().split() for _ in range(N) 
                for _ in range(N)], int).reshape((N, M))
    min1 = np.min(arr, axis = 1)
    max0 = np.max(min1)
    return max

sample_input = input()
print(min1_max0(sample_input)

### 변수랑 input() 연결 시 괄호 주의!
### 위 코드 실행하니까 아래 같은 오류 나옴 

### Trace back (most recent call last):
  File "Solution.py", line 12, in <module>
  File "Solution.py", line 5, in min1_max0
  File "Solution.py", line 6, in <listcomp>
EOFError

In [65]:
np.array([['1', '4'], ['3', '6'], ['4', '7']], int).reshape((2, 3))

array([[1, 4, 3],
       [6, 4, 7]])

In [ ]:
### 예시답안 using function
def sample_input_func(x):
    return list(map(int, x.split()))

def main():
    N, M = sample_input_func(input())
    initial_array = np.array([sample_input_func(input()) for _ in range(N)])
    min_array = np.min(initial_array, axis = 1)
    max_Array = np.max(min_array, axis = 0)
    print(max_array)
    
main()
    
    

### 여러 개의 input 들어갈 때는 함수의 인수를 비워둬야 하는 건가베?

- Mean, Var and Std

In [ ]:
import numpy as np
N, M = map(int, input().split())
arr = np.array([input().split() for _ in range(N)], int)
Mean = np.mean(arr, axis = 1)
Var = np.var(arr, axis = 0)
Std = np.std(arr)
print(Mean, Var, Std, sep = '\n')

In [67]:
arr = np.arange(12).reshape(3, 4)

In [68]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
Mean = np.mean(arr, axis = 1)
Var = np.var(arr, axis = 0)
Std = np.std(arr)
print(Mean, Var, Std, sep = '\n')

[1.5 5.5 9.5]
[10.66666667 10.66666667 10.66666667 10.66666667]
3.452052529534663


In [71]:
Mean = np.mean(arr, axis = 1)
Var = np.var(arr, axis = 0)
Std = np.std(arr, axis = None)
print(Mean, Var, Std, sep = '\n')

[1.5 5.5 9.5]
[10.66666667 10.66666667 10.66666667 10.66666667]
3.452052529534663


In [ ]:
import numpy as np
N, M = map(int, input().split())
arr = np.array([input().split() for _ in range(N)], int)
Mean = np.mean(arr, axis = 1)
Var = np.var(arr, axis = 0)
Std = np.std(arr)

np.set_printoptions(legacy = '1.13')

print(Mean, Var, Std, sep = '\n')

- Dot and Cross

In [73]:
import numpy as np

A = np.array([1, 2])
B = np.array([3, 4])

np.dot(A, B)

11

In [74]:
np.cross(A, B)

array(-2)

In [75]:
type(np.dot(A, B))

numpy.int32

In [77]:
type(np.cross(A, B))

numpy.ndarray

In [78]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 2], [3, 4]])
np.dot(A, B)

array([[ 7, 10],
       [15, 22]])

In [ ]:
import numpy as np

N = int(input())
A = np.array([input().split() for _ in range(N)], int)
B = np.array([input().split() for _ in range(N)], int)
Dot = np.dot(A, B)
print(Dot)

- transpose and flatten

In [ ]:
import numpy as np

N, M = map(int, input().split())
arr = np.array([input().split() for _ in range(N)], int)
T = np.transpose(arr)
F = arr.flatten()
print(T, F, sep = '\n')