In [1]:
import re

In [4]:
match_object = re.match('\d+', '123455')

In [5]:
match_object.start()

0

In [7]:
match_object.end()

6

In [8]:
import numpy as np 

In [9]:
np.poly('12345')

array([ 1.0000e+00, -1.2345e+04])

In [10]:
np.poly([1, 2, 3, 4, 5])

array([   1.,  -15.,   85., -225.,  274., -120.])

In [11]:
arr = np.array(range(5))

In [12]:
np.poly(arr)

array([  1., -10.,  35., -50.,  24.,   0.])

In [13]:
arr = np.array(range(1, 6))

In [14]:
np.poly(arr)

array([   1.,  -15.,   85., -225.,  274., -120.])

In [15]:
np.roots('123456')

array([], dtype=float64)

In [16]:
np.roots(np.array(range(5)))

array([-1.65062919+0.j        , -0.1746854 +1.54686889j,
       -0.1746854 -1.54686889j])

In [17]:
import functools

In [19]:
functools.reduce(lambda x, y: ''.join([x, y]), ['a', 'b', 'c', 'd'], '')

'abcd'

In [20]:
functools.reduce(lambda x, y: ''.join([x, y]), ['a', 'b', 'c', 'd'], 'z')

'zabcd'

In [21]:
x, y = map(int, ['3', '4'])

In [22]:
x

3

In [23]:
y

4

In [24]:
z, w = [[3, 4], [7, 8]]

In [25]:
z

[3, 4]

In [26]:
w

[7, 8]

In [27]:
z, w = [[3, 4], [1, 3], [1, 1]]

ValueError: too many values to unpack (expected 2)

In [28]:
numbers = [[3, 4], [8, 8], [9, 1], [3, 3]]

In [29]:
import fractions

In [30]:
list(map(lambda x, y: fractions.Fraction(x, y), numbers))

TypeError: <lambda>() missing 1 required positional argument: 'y'

In [31]:
map(lambda x, y: fractions.Fraction(x, y), [7, 8])

In [32]:
list(map(lambda x, y: fractions.Fraction(x, y), [7, 8]))

TypeError: <lambda>() missing 1 required positional argument: 'y'

In [33]:
zip('12345', '56788')

In [34]:
test = zip('12345', '56788')

In [35]:
list(zip('12345', '56788'))

[('1', '5'), ('2', '6'), ('3', '7'), ('4', '8'), ('5', '8')]

In [36]:
list(test)

[('1', '5'), ('2', '6'), ('3', '7'), ('4', '8'), ('5', '8')]

In [37]:
test

In [38]:
list(test)

[]

In [39]:
match_object

<re.Match object; span=(0, 6), match='123455'>

In [40]:
match_object.group()

'123455'

In [41]:
match_object

<re.Match object; span=(0, 6), match='123455'>

In [42]:
sum(map(int, '12356'))

17

In [43]:
sum(*map(int, '123456'))

TypeError: sum() takes at most 2 arguments (6 given)

In [44]:
int([])

TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

In [45]:
int(*[])

0

In [46]:
int(None)

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

In [47]:
print(*[])

In [48]:
print()

In [49]:
print(None)

None


In [50]:
key = 1, 2, 3

In [51]:
key 

(1, 2, 3)

In [52]:
import itertools

In [53]:
itertools.groupby('11122223')

In [67]:
groupby_object = itertools.groupby('11122223')

In [65]:
list(groupby_object)

[('1', <itertools._grouper at 0x21861134be0>),
 ('2', <itertools._grouper at 0x218611347c0>),
 ('3', <itertools._grouper at 0x21861134ee0>)]

In [68]:
[(x, list(y)) for x, y in list(groupby_object)]

[('1', []), ('2', []), ('3', [])]

In [61]:
for key, group in itertools.groupby('1112223'):
    print(key, list(group))

1 ['1', '1', '1']
2 ['2', '2', '2']
3 ['3']


In [69]:
floor(3.5)

NameError: name 'floor' is not defined

In [70]:
import math

In [71]:
math.floor(3.5)

3

In [79]:
np.concatenate(np.array([3, 4, 5]), np.array([5, 6, 7]), axis = 0)

TypeError: concatenate() got multiple values for argument 'axis'